### ISSUE TITLE
include URL

### ISSUE THREAD

**Issue by jetmore** [swesteme/artifact-version-service#1]
Could the library pull in project URL? I know that's kind of obscure but the first thing I wanted to use it for was to create a user agent string.

**Comment by swesteme** [comment]
I have added URL and description. Will upload a release now, you can then start using version 1.1.0 for service and maven plugin. Let me know if it works out for you!

**Comment by swesteme** [comment]
@jetmore the library version 1.1.0 should now be available through maven central.

**Comment by jetmore** [comment]
Finally implementing this and it works great, thanks!

**Comment by swesteme** [comment]
You‘re welcome, I am happy to hear people actually use the library 😜
